# Generated by Django 6.0.2 on 2026-02-24 03:53

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries ={
        "published":"A Post avaible for all to view",
        "daft":"A post only visible to the author",
        "archived":"An odler post visble only to the logged user"
    }
    Status = apps.get_model("posts","Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_status'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
