# Generated by Django 6.0.2 on 2026-02-27 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
    ]
